src/Entity/DiscoVinil.php
<?php

namespace App\Entity;

use App\Repository\DiscoVinilRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: DiscoVinilRepository::class)]
class DiscoVinil
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titulo = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $descricao = null;

    #[ORM\Column]
    private ?int $contaFaixas = null;

    #[ORM\Column(length: 255)]
    private ?string $genero = null;

    #[ORM\Column]
    private int $votos = 0;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['titulo'])]
    private ?string $slug = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(?string $descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getContaFaixas(): ?int
    {
        return $this->contaFaixas;
    }

    public function setContaFaixas(int $contaFaixas): self
    {
        $this->contaFaixas = $contaFaixas;

        return $this;
    }

    public function getGenero(): ?string
    {
        return $this->genero;
    }

    public function setGenero(string $genero): self
    {
        $this->genero = $genero;

        return $this;
    }

    public function getVotos(): ?int
    {
        return $this->votos;
    }

    public function setVotos(int $votos): self
    {
        $this->votos = $votos;

        return $this;
    }

    public function upVoto(): void
    {
        $this->votos++;
    }

    public function downVoto(): void
    {
        $this->votos--;
    }

    public function getVotosString(): string
    {
        $prefix = ($this->votos === 0) ? '' : (($this->votos >= 0) ? '+' : '-');

        return sprintf('%s %d', $prefix, abs($this->votos));
    }

    public function getImageUrl(int $width): string
    {
        return sprintf(
            'https://picsum.photos/id/%d/%d',
            ($this->getId() + 50) % 1000, // number between 0 and 1000, based on the id
            $width
        );
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/DiscoController.php
<?php

namespace App\Controller;

use App\Entity\DiscoVinil;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DiscoController extends AbstractController
{
    #[Route('/disco/novo')]
    public function new(EntityManagerInterface $entityManager): Response
    {
        
    }

    #[Route('/disco/{slug}', name: 'app_disco_show')]
    public function show(DiscoVinil $disco): Response
    {
        return $this->render('disco/show.html.twig', [
            'disco' => $disco,
        ]);
    }

    #[Route('/disco/{id}/voto', name: 'app_disco_voto', methods: ['POST'])]
    public function voto(DiscoVinil $disco, Request $request, EntityManagerInterface $entityManager): Response
    {
        $direction = $request->request->get('direction', 'up');
        if($direction === 'up'){
            $disco->upVoto();
        }else{
            $disco->downVoto();
        }
        
        $entityManager->flush();

        $this->addFlash('sucesso', 'Voto enviado!');

        return $this->redirectToRoute('app_disco_show', [
            'slug' => $disco->getSlug()
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use function Symfony\Component\String\u;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function index(): Response
    {
        $tracks = [
            ['id' => 1, 'song' => 'Gangsta\'s Paradise', 'artist' => 'Coolio'],
            ['id' => 2, 'song' => 'Waterfalls', 'artist' => 'TLC'],
            ['id' => 3, 'song' => 'Creep', 'artist' => 'Radiohead'],
            ['id' => 4, 'song' => 'Kiss from a Rose', 'artist' => 'Seal'],
            ['id' => 5, 'song' => 'On Bended Knee', 'artist' => 'Boyz II Men'],
            ['id' => 6, 'song' => 'Fantasy', 'artist' => 'Mariah Carey'],
        ];

        return $this->render('home/index.html.twig', [
            'title' => 'PB & Jams',
            'tracks' => $tracks,
        ]);
    }

    #[Route('/pesquisar/{slug}', name: 'app_pesquisar')]
    public function pesquisar(string $slug = null): Response
    {
        $genre = $slug ? u(str_replace('-', ' ', $slug))->title(true) : null;

        return $this->render('home/pesquisar.html.twig', [
            'genre' => $genre
        ]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use function Symfony\Component\String\u;

class SongController extends AbstractController
{
    #[Route('api/songs/{id<\d+>}', methods: ['GET'], name: 'api_songs_get_one')]
    public function getSong(int $id, LoggerInterface $logger): Response
    {
        // TODO query the database
        $song = [
            'id' => $id,
            'name' => 'Waterfalls',
            'url' => 'https://symfonycasts.s3.amazonaws.com/sample.mp3',
        ];

        $logger->info('Returning API response for song {song}', [
            'song' => $id,
        ]);

        return $this->json($song);
    }
}

src/Controller/VinilController.php
<?php

namespace App\Controller;

use App\Repository\DiscoVinilRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

use function Symfony\Component\String\u;

class VinilController extends AbstractController
{
    #[Route('/', name: 'app_homepage')]
    public function index(): Response
    {
        $tracks = [
            ['id' => 1, 'song' => 'Gangsta\'s Paradise', 'artist' => 'Coolio'],
            ['id' => 2, 'song' => 'Waterfalls', 'artist' => 'TLC'],
            ['id' => 3, 'song' => 'Creep', 'artist' => 'Radiohead'],
            ['id' => 4, 'song' => 'Kiss from a Rose', 'artist' => 'Seal'],
            ['id' => 5, 'song' => 'On Bended Knee', 'artist' => 'Boyz II Men'],
            ['id' => 6, 'song' => 'Fantasy', 'artist' => 'Mariah Carey'],
        ];

        return $this->render('home/index.html.twig', [
            'title' => 'PB & Jams',
            'tracks' => $tracks,
        ]);
    }

    #[Route('/pesquisar/{slug}', name: 'app_pesquisar')]
    public function pesquisar(DiscoVinilRepository $discoRepository, Request $request, string $slug = null): Response
    {
        $genre = $slug ? u(str_replace('-', ' ', $slug))->title(true) : null;

        $queryBuilder = $discoRepository->createOrderedByVotesQueryBuilder($slug);
        $adapter = new QueryAdapter($queryBuilder);
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $request->query->get('page', 1),
            9
        );

        return $this->render('home/pesquisar.html.twig', [
            'genre' => $genre,
            'pager' => $pagerfanta
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Discos de Vinil{% endblock %}</title>

        <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">

        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>

        <!-- Main Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark  mb-5" style="background-color: #27333A;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ path('app_homepage') }}">
                    <i class="fas fa-record-vinyl"></i>
                    Discos de Vinil
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="margin-top: 20px;" href="{{ path('app_pesquisar') }}">Buscar Discos</a>
                        </li>
                        <!-- Not Authenticated -->
                            <!-- <li class="nav-item"><button href="#" class="btn btn-primary btn-sm">Login</button></li> -->
                        <!-- End Not Authenticated -->

                        <!-- If Authenticated -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user-astronaut p-2" style="border: solid 1px #fff; border-radius: 50px; font-size: 40px;"></i>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="#">Meus Discos</a></li>
                                <li><a class="dropdown-item" href="#">Sair</a></li>
                            </ul>
                        </li>
                        <!-- End If Authenticated -->
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End Main Navigation -->

        {% for message in app.flashes('sucesso') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {% block body %}{% endblock %}

        <!-- Footer -->
        <div class="container mt-5">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <div class="col-md-6 d-flex align-items-center">
                    <span class="me-1" style="color: red;"><i class="fas fa-heart"></i></span>
                    <span class="text-muted me-1">Desenvolvido por</span>
                    <a target="_blank" href="https://github.com/luangouveiax" style="color: #25a1dd" class="mb-3 me-2 mb-md-0 text-decoration-none lh-1">
                        Luan Xavier
                    </a>
                    <span class="text-muted me-1">com Symfony framework</span>
                </div>

                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3"><a class="text-muted" target="_blank" href="https://github.com/luangouveiax/disco-vinil-symfony"><i class="fab fa-github"></i></a></li>
                </ul>
            </footer>
        </div>
        <!-- End Footer -->

    </body>
</html>

templates/disco/_recordSvg.html.twig
<svg width="100%" height="100%" viewBox="0 0 496 496" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#C380F3" offset="0%"></stop>
            <stop stop-color="#4A90E2" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="Mixed-Vinyl" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group">
            <g id="record-vinyl" fill="#000000" fill-rule="nonzero">
                <path d="M248,144 C190.562386,144 144,190.562386 144,248 C144,305.437614 190.562386,352 248,352 C305.437614,352 352,305.437614 352,248 C352,190.562386 305.437614,144 248,144 L248,144 Z M248,272 C234.745166,272 224,261.254834 224,248 C224,234.745166 234.745166,224 248,224 C261.254834,224 272,234.745166 272,248 C272,261.254834 261.254834,272 248,272 Z M248,0 C111,0 0,111 0,248 C0,385 111,496 248,496 C385,496 496,385 496,248 C496,111 385,0 248,0 Z M248,376 C177.307552,376 120,318.692448 120,248 C120,177.307552 177.307552,120 248,120 C318.692448,120 376,177.307552 376,248 C376,281.947711 362.514324,314.505012 338.509668,338.509668 C314.505012,362.514324 281.947711,376 248,376 Z" id="Shape"></path>
            </g>
            <g id="record-vinyl" transform="translate(144.000000, 144.000000)" fill="url(#linearGradient-1)" fill-rule="nonzero">
                <path d="M104,0 C46.562386,0 0,46.562386 0,104 C0,161.437614 46.562386,208 104,208 C161.437614,208 208,161.437614 208,104 C208,46.562386 161.437614,0 104,0 L104,0 Z M104,128 C90.745166,128 80,117.254834 80,104 C80,90.745166 90.745166,80 104,80 C117.254834,80 128,90.745166 128,104 C128,117.254834 117.254834,128 104,128 Z" id="Shape"></path>
            </g>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="235"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="215"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="195"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="175"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="155"></circle>
        </g>
    </g>
</svg>

templates/disco/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}{{ disco.titulo }} Disco{% endblock %}

{% block body %}
<div class="container">
    <h1 class="d-inline me-3">{{ disco.titulo }}</h1> <i class="fas fa-edit"></i>
    <div class="row mt-5">
        <div class="col-12 col-md-4">
            {{ include('disco/_recordSvg.html.twig') }}
        </div>
        <div class="col-12 col-md-8 ps-5">
            <h2 class="mb-4">{{ disco.contaFaixas }} faixas <small>(genero: {{ disco.genero }})</small></h2>
            <p>{{ disco.descricao }}</p>

            {{ disco.votos }} votos

            <form action="{{ path('app_disco_voto', {id: disco.id}) }}" method="POST">
                <button
                    type="submit"
                    class="btn btn-outline-primary"
                    name="direction"
                    value="up"
                >
                    <span class="fa fa-thumbs-up"></span>
                </button>
                <button
                    type="submit"
                    class="btn btn-outline-primary"
                    name="direction"
                    value="down"
                >
                    <span class="fa fa-thumbs-down"></span>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Criar novo Cadastro | {{ parent() }}{% endblock %}

{% block body %}
<div class="container">
    <h1 class="d-inline me-3">{{ title }}</h1> <i class="fas fa-edit"></i>
    <div class="row mt-5">
        <div class="col-12 col-md-4">
           {{ include('disco/_recordSvg.html.twig') }}
        </div>
        <div class="col-12 col-md-8 ps-5">
            <h2 class="mb-4">10 músicas (30 minutos de 60 ainda disponíveis)</h2>
            {% for track in tracks %}
            <div class="song-list" {{ stimulus_controller('song-controls', {
                infoUrl: path('api_songs_get_one', { id: track.id })
            }) }}>
                <div class="d-flex mb-3">
                    <a href="#" {{ stimulus_action('song-controls', 'play') }}>
                        <i class="fas fa-play me-3"></i>
                    </a>
                    <span class="song-details">{{ track.song }} - {{ track.artist }}</span>
                    <a href="#">
                        <i class="fas fa-bars mx-3"></i>
                    </a>
                    <a href="#">
                        <i class="fas fa-times"></i>
                    </a>
                </div>
            </div>
            {% endfor %}
            <button type="button" class="btn btn-success"><i class="fas fa-plus"></i> Adicionar</button>
        </div>
    </div>
</div>
{% endblock %}

templates/home/pesquisar.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <h1>Pesquisando por {{ genre ? genre : 'Todos os Gêneros' }}</h1>

    <h2 class="mt-5 mb-4">Filtrar por Gênero</h2>
    <ul class="genre-list ps-0 mt-2 mb-3">
        <li class="d-inline">
            <a class="btn btn-primary btn-sm" href="{{ path('app_pesquisar', {
                slug: 'mpb'
            }) }}">MPB</a>
        </li>
        <li class="d-inline">
            <a class="btn btn-primary btn-sm" href="{{ path('app_pesquisar', {
                slug: 'rock'
            }) }}">Rock</a>
        </li>
        <li class="d-inline">
            <a class="btn btn-primary btn-sm" href="{{ path('app_pesquisar', {
                slug: 'heavy-metal'
            }) }}">Heavy Metal</a>
        </li>
    </ul>

    <div>
        <h2 class="mt-5">Discos</h2>
        <turbo-frame id="lista_disco_pesquisa_{{ pager.currentPage }}">
            <div class="row">
                {% for disco in pager %}
                <div class="col col-md-4">
                    <a 
                        href="{{ path('app_disco_show', {
                            slug: disco.slug
                        }) }}"
                        style="color:#fff; text-decoration:none;"
                    >
                        <div class="mixed-vinyl-container p-3 text-center">
                            <img src="{{ disco.imageUrl(300) }}" alt="Capa Album">
                            <p class="mt-2"><strong>{{ disco.titulo }}</strong></p>
                            <span>{{ disco.contaFaixas }} Faixas</span>
                            |
                            <span>{{ disco.genero }}</span>
                            |
                            <span>{{ disco.createdAt|ago(locale='pt-BR') }}</span>
                            <br>
                            {{ disco.votosString }} votos
                        </div>
                    </a>
                </div>
                {% endfor %}

                {% if pager.hasNextPage %}
                    <turbo-frame 
                        id="lista_disco_pesquisa_{{ pager.nextPage }}" 
                        src="{{ pagerfanta_page_url(pager, pager.nextPage) }}" 
                        loading="lazy">
                    </turbo-frame>
                {% endif %}
            </div>
        </turbo-frame>
    </div>
</div>
{% endblock %}